name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - accelerate=1.5.2
  - cuda-version=12.6
  - diffusers=0.32.2
  - ipympl=0.9.6
  - matplotlib=3.10.1
  - notebook=7.3.3
  - numpy=2.2.4
  - plotly=6.0.1
  - python-graphviz=0.20.3
  - pytorch-gpu=2.6.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - timm=1.0.15
  - torchvision=0.21.0
  - transformers=4.49.0
